### ISSUE TITLE
TME1 Submission Checklist

### ISSUE THREAD

**Issue by nevantan** [nevantan/comp308#1]
# Program 1
## Testing
- [x] Test plan included
- [x] Tests for valid conditions
- [x] Tests for error conditions

## Documentation
- [x] Problem description and detailed requirements
- [x] Program, name, student ID, date, statement of purpose
- [x] Compile and run instructions
- [x] Document individual methods
- [x] Document complex logic
- [x] Purpose of main variable and method names

# Program 2
## Testing
- [ ] Test plan included
- [ ] Tests for valid conditions
- [ ] Tests for error conditions

## Documentation
- [ ] Problem description and detailed requirements
- [ ] Program, name, student ID, date, statement of purpose
- [ ] Compile and run instructions
- [ ] Document individual methods
- [ ] Document complex logic
- [ ] Purpose of main variable and method names

# Program 3
## Testing
- [ ] Test plan included
- [ ] Tests for valid conditions
- [ ] Tests for error conditions

## Documentation
- [ ] Problem description and detailed requirements
- [ ] Program, name, student ID, date, statement of purpose
- [ ] Compile and run instructions
- [ ] Document individual methods
- [ ] Document complex logic
- [ ] Purpose of main variable and method names

# Program 4
## Testing
- [ ] Test plan included
- [ ] Tests for valid conditions
- [ ] Tests for error conditions

## Documentation
- [ ] Problem description and detailed requirements
- [ ] Program, name, student ID, date, statement of purpose
- [ ] Compile and run instructions
- [ ] Document individual methods
- [ ] Document complex logic
- [ ] Purpose of main variable and method names

# Packaging
- [ ] All files in a single zip
- [ ] All program solution source code in a single directory
- [ ] Compiles with `javac *.java`
- [ ] Runs without error

# Other Points
- [ ] Include the final deliverable only
- [ ] Include examples, code fragments, etc. to illustrate points in the Q&A portion of the assignment
